hosts:
- mac: "1c:69:7a:60:d0:c4"
  kernel:
    path: "deps/amd64/kernel"
  initrds:
  - path: "deps/amd64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/amd64/root.img
    gzip: true
  boot_args:
  - "netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  secrets:
  - id: /cloud_init/users/admin/password
    type: password
  vars:
    cloud_init:
      hostname: jules
      users:
      - name: admin
        password: '{{ (secret "/cloud_init/users/admin/password") }}'
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh
      runcmds:
      - "systemctl enable sshd"
      - "systemctl start --no-block sshd"
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/nvme0n1
        mounts:
        - partition: /dev/nvme0n1p2
          path: /root
- mac: "f0:ad:4e:10:1b:87"
  force_pxe_linux: true
  kernel:
    path: "deps/arm64/kernel"
  initrds:
  - path: "deps/arm64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/arm64/root.img
    gzip: true
  boot_args:
  - "console=ttyMV0,115200 earlycon=ar3700_uart,0xd0012000 netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  vars:
    cloud_init:
      hostname: ceph2
      users:
      - name: admin
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh-server
      networks:
      - interface: eth0
      - interface: lan0
      bootcmds:
      # The root image is built with qemu which has a tty of ttyAMA0, but the espressobin uses ttyMV0.
      - "rm -rf /etc/systemd/system/getty.target.wants/serial-getty@ttyAMA0.service"
      - "if [ ! -e /etc/systemd/system/getty.target.wants/serial-getty@ttyMV0.service ]; then ln -s /lib/systemd/system/serial-getty@.service /etc/systemd/system/getty.target.wants/serial-getty@ttyMV0.service; fi"
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/sdb
        mounts:
        - partition: /dev/sdb4
          path: /root
- mac: "f0:ad:4e:10:1b:32"
  force_pxe_linux: true
  kernel:
    path: "deps/arm64/kernel"
  initrds:
  - path: "deps/arm64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/arm64/root.img
    gzip: true
  boot_args:
  - "console=ttyMV0,115200 earlycon=ar3700_uart,0xd0012000 netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  vars:
    cloud_init:
      hostname: ceph3
      users:
      - name: admin
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh-server
      networks:
      - interface: eth0
      - interface: lan0
      bootcmds:
      # The root image is built with qemu which has a tty of ttyAMA0, but the espressobin uses ttyMV0.
      - "rm -rf /etc/systemd/system/getty.target.wants/serial-getty@ttyAMA0.service"
      - "if [ ! -e /etc/systemd/system/getty.target.wants/serial-getty@ttyMV0.service ]; then ln -s /lib/systemd/system/serial-getty@.service /etc/systemd/system/getty.target.wants/serial-getty@ttyMV0.service; fi"
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/sdb
        mounts:
        - partition: /dev/sdb4
          path: /root
- mac: "f0:ad:4e:10:1b:af"
  force_pxe_linux: true
  kernel:
    path: "deps/arm64/kernel"
  initrds:
  - path: "deps/arm64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/arm64/root.img
    gzip: true
  boot_args:
  - "console=ttyMV0,115200 earlycon=ar3700_uart,0xd0012000 netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  vars:
    cloud_init:
      hostname: ceph4
      users:
      - name: admin
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh-server
      networks:
      - interface: eth0
      - interface: lan0
      bootcmds:
      # The root image is built with qemu which has a tty of ttyAMA0, but the espressobin uses ttyMV0.
      - "rm -rf /etc/systemd/system/getty.target.wants/serial-getty@ttyAMA0.service"
      - "if [ ! -e /etc/systemd/system/getty.target.wants/serial-getty@ttyMV0.service ]; then ln -s /lib/systemd/system/serial-getty@.service /etc/systemd/system/getty.target.wants/serial-getty@ttyMV0.service; fi"
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/sdb
        mounts:
        - partition: /dev/sdb4
          path: /root
- mac: "b8:27:eb:cb:9e:35"
  kernel:
    path: "deps/arm64/kernel"
  initrds:
  - path: "deps/arm64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/arm64/root.img
    gzip: true
  boot_args:
  - "console=ttyAMA0,115200 console=tty1 netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  vars:
    cloud_init:
      hostname: unifi
      users:
      - name: admin
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh-server
      networks:
      - addresses: [192.168.1.100/24]
        gateway: 192.168.1.1
        dns_servers:
        - 8.8.8.8
        - 1.1.1.1
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/sda
        mounts:
        - partition: /dev/sda4
          path: /root
- mac: "b8:27:eb:87:cf:c5"
  kernel:
    path: "deps/arm64/kernel"
  initrds:
  - path: "deps/arm64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/arm64/root.img
    gzip: true
  boot_args:
  - "console=ttyAMA0,115200 console=tty1 netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  vars:
    cloud_init:
      hostname: ceph0
      users:
      - name: admin
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh-server
      networks:
      - interface: eth0
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/sda
        mounts:
        - partition: /dev/sda4
          path: /root
- mac: "b8:27:eb:5b:05:63"
  kernel:
    path: "deps/arm64/kernel"
  initrds:
  - path: "deps/arm64/initrd"
  files:
  - id: cloud_init_metadata
    path: configs/shared/meta-data
    template: true
  - id: cloud_init_networking
    path: configs/shared/network-config
    template: true
  - id: cloud_init_userdata
    path: configs/shared/user-data
    template: true
  - id: disk_image
    path: deps/arm64/root.img
    gzip: true
  boot_args:
  - "console=ttyAMA0,115200 console=tty1 netboot_installer={{ .vars.installer | toRawJson | b64enc }}"
  vars:
    cloud_init:
      hostname: ceph1
      users:
      - name: admin
        authorized_keys:
        - '{{ (shared_secret "/cloud_init/users/admin/ssh_key").public_key }}'
      packages:
      - openssh-server
      networks:
      - interface: eth0
    installer:
      files:
      - url: '{{ file_url "cloud_init_metadata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/meta-data
      - url: '{{ file_url "cloud_init_networking" }}'
        dest: /root/var/lib/cloud/seed/nocloud/network-config
      - url: '{{ file_url "cloud_init_userdata" }}'
        dest: /root/var/lib/cloud/seed/nocloud/user-data
      disks:
      - url: '{{ file_url "disk_image" }}'
        gzip: true
        dest_device: /dev/sda
        mounts:
        - partition: /dev/sda4
          path: /root
shared_secrets:
- id: /cloud_init/users/admin/ssh_key
  type: ssh_key
