#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${BOSH_DIRECTOR_SECRETS:?}

read_with_escaped_newlines() {
  perl -pe 's|\n|\\n|' "$1"
}

yaml_to_json() {
  echo "$1" | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))'
}

secrets_json="$(yaml_to_json "${BOSH_DIRECTOR_SECRETS}")"

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
cpi_dir="$( cd "${workspace_dir}/cpi-release" && pwd )"
bosh_dir="$( cd "${workspace_dir}/bosh-release" && pwd )"
stemcell_dir="$( cd "${workspace_dir}/stemcell" && pwd )"
ssl_certs_dir="$( cd "${workspace_dir}/ssl-certs" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

# outputs
output_dir="$( cd "${workspace_dir}/updated-deployments-src" && pwd )"
mkdir -p "${output_dir}"

pushd "${deployments_dir}" > /dev/null
  cp -R . "${output_dir}/"
popd > /dev/null

working_dir="$( cd "${output_dir}/bosh/" && pwd )"
mkdir -p "${working_dir}/assets/"
cp ${cpi_dir}/*.tgz "${working_dir}/assets/cpi.tgz"
cp ${bosh_dir}/*.tgz "${working_dir}/assets/bosh.tgz"
cp ${stemcell_dir}/*.tgz "${working_dir}/assets/stemcell.tgz"

function finish() {
  pushd "${output_dir}" > /dev/null
    echo "Checking whether state file has changed..."

    set +e
    git status --porcelain | grep '.*-state.json' 1> /dev/null
    state_changed=$?
    set -e

    if [ "${state_changed}" == "0" ]; then
      echo "Committing state file changes..."
      git add ./bosh/*-state.json
      git clean -df && git checkout -- . # clean slate to allow pull + rebase
      git config --global user.email "lylejfranklin@gmail.com"
      git config --global user.name "friendly-ci"
      git commit -m ":airplane: Auto-commit: Updating Director deployment state"
    fi

    echo "Finished deploy director task!"
  popd > /dev/null
}
trap finish EXIT

pushd "${working_dir}" > /dev/null
  echo "Updating director..."
  ${bosh_cli} -n create-env \
    -l <(echo "${BOSH_DIRECTOR_SECRETS}") \
    -l "${terraform_config}/metadata" \
    -v ssl_cert="$( read_with_escaped_newlines ${ssl_certs_dir}/certificates/*.crt )" \
    -v ssl_key="$( read_with_escaped_newlines ${ssl_certs_dir}/certificates/*.key )" \
    ./director.yml

  echo "Updating cloud config..."
  director_endpoint="$( jq -e -r .bosh_hostname "${terraform_config}/metadata" )"
  director_username="$( echo "${secrets_json}" | jq -e -r .director_admin_username )"
  director_password="$( echo "${secrets_json}" | jq -e -r .director_admin_password )"
  ${bosh_cli} -n update-cloud-config \
    --environment "${director_endpoint}" \
    --user "${director_username}" \
    --password "${director_password}" \
    ./cloud-config.yml
popd > /dev/null

echo "Successfully updated director!"
