#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${BOSH_DIRECTOR_SECRETS:?}

yaml_to_json() {
  echo "$1" | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))'
}

secrets_json="$(yaml_to_json "${BOSH_DIRECTOR_SECRETS}")"

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
cpi_dir="$( cd "${workspace_dir}/cpi-release" && pwd )"
bosh_dir="$( cd "${workspace_dir}/bosh-release" && pwd )"
stemcell_dir="$( cd "${workspace_dir}/stemcell" && pwd )"
ssl_certs_dir="$( cd "${workspace_dir}/ssl-certs" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

# outputs
output_dir="$( cd "${workspace_dir}/output-src" && pwd )"

git clone "${deployments_dir}" "${output_dir}"

working_dir="$( cd "${output_dir}/bosh/" && pwd )"
mkdir -p "${working_dir}/assets/"
cp ${cpi_dir}/*.tgz "${working_dir}/assets/cpi.tgz"
cp ${bosh_dir}/*.tgz "${working_dir}/assets/bosh.tgz"
cp ${stemcell_dir}/*.tgz "${working_dir}/assets/stemcell.tgz"

pushd "${working_dir}" > /dev/null
  echo "Updating director..."
  ${bosh_cli} -n create-env \
    -l <(echo "${BOSH_DIRECTOR_SECRETS}") \
    -l "${terraform_config}/metadata" \
    --var-file ssl_cert="$( echo ${ssl_certs_dir}/certificates/*.crt )" \
    --var-file ssl_key="$( echo ${ssl_certs_dir}/certificates/*.key )" \
    ./director.yml

  echo "Updating cloud config..."
  export BOSH_ENVIRONMENT="$( jq -e -r .bosh_hostname "${terraform_config}/metadata" )"
  export BOSH_CLIENT="$( echo "${secrets_json}" | jq -e -r .director_admin_username )"
  export BOSH_CLIENT_SECRET="$( echo "${secrets_json}" | jq -e -r .director_admin_password )"
  ${bosh_cli} -n update-cloud-config ./cloud-config.yml
popd > /dev/null

echo "Successfully updated director!"
