#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${GCP_CREDENTIALS_JSON:?}
: ${BOSH_BOT_SECRETS:?}

# inputs
terraform_config="$( cd "${workspace_dir}/terraform" && pwd )"
ssl_certs_dir="$( cd "${workspace_dir}/ssl-certs" && pwd )"
bosh_deployment_dir="$( cd "${workspace_dir}/bosh-deployment" && pwd )"
bosh_bot_dir="$( cd "${workspace_dir}/bosh-bot" && pwd )"
input_vars_store="$( cd "${workspace_dir}/director-vars-store" && pwd )"
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

# outputs
output_vars_store="$( cd "${workspace_dir}/updated-director-vars-store" && pwd )"
output_dir="$( cd "${workspace_dir}/output-src" && pwd )"

git clone "${deployments_dir}" "${output_dir}"
cp "${input_vars_store}/vars-store.yml" "${output_vars_store}"

working_dir="$( cd "${output_dir}/bosh/" && pwd )"

pushd "${working_dir}" > /dev/null
  echo "Updating director..."
  ${bosh_cli} -n create-env \
    --vars-store "${output_vars_store}/vars-store.yml" \
    --state ./director-state.json \
    -o "${bosh_deployment_dir}/gcp/cpi.yml" \
    -o "${bosh_deployment_dir}/external-ip-not-recommended.yml" \
    -o "${bosh_deployment_dir}/jumpbox-user.yml" \
    -o "${bosh_deployment_dir}/local-dns.yml" \
    -o ./ops/ssl-cert.yml \
    -o ./ops/default-ssh.yml \
    -o ./ops/service-scopes.yml \
    -o "${bosh_bot_dir}/bosh/bosh-ops-file.yml" \
    -l "${terraform_config}/metadata" \
    -l <( echo "${BOSH_BOT_SECRETS}" ) \
    --var-file ssl_cert="$( ls ${ssl_certs_dir}/certificates/*.crt | grep -v 'issuer.crt')" \
    --var-file ssl_key="$( echo ${ssl_certs_dir}/certificates/*.key )" \
    -v director_name=bosh \
    -v gcp_credentials_json="'${GCP_CREDENTIALS_JSON}'" \
    "${bosh_deployment_dir}/bosh.yml"

  echo "Updating cloud config..."
  export BOSH_ENVIRONMENT="$( jq -e -r .bosh_hostname "${terraform_config}/metadata" )"
  export BOSH_CLIENT="admin"
  export BOSH_CLIENT_SECRET="$( ${bosh_cli} interpolate --path /admin_password "${output_vars_store}/vars-store.yml" )"
  ${bosh_cli} -n update-cloud-config ./cloud-config.yml
popd > /dev/null

echo "Successfully updated director!"
