---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/deployments

inputs:
  - name: terraform
  - name: deployments-src
  - name: bosh-cli
  - name: ssl-certs
  - name: bosh-deployment
  - name: bosh-bot
  - name: director-vars-store

outputs:
  - name: output-src
  - name: updated-director-vars-store

params:
  GCP_CREDENTIALS_JSON: ""
  BOSH_BOT_SECRETS: ""

run:
  path: deployments-src/ci/setup-env/tasks/deploy-director
