---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/deployments

inputs:
  - name: terraform
  - name: deployments-src
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: bosh-cli
  - name: ssl-certs

outputs:
  - name: output-src

params:
  BOSH_DIRECTOR_SECRETS: ""

run:
  path: deployments-src/ci/setup-env/tasks/deploy-director
