#!/bin/bash

set -eu -o pipefail

deployments_dir="$( cd "$( dirname "$0" )" && cd ../../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# ENV
: "${GCP_CREDENTIALS_JSON}"

# OUTPUTS
output_dir="${workspace_dir}/gcp-firewall-rules"

gcloud auth activate-service-account --key-file=<( echo "${GCP_CREDENTIALS_JSON}" )

# example format:
# {
#   "google_compute_firewall.allow-ssh": "allow-ssh",
#   "google_compute_firewall.allow-bosh": "allow-bosh"
# }
gcloud compute firewall-rules list --format json --filter network=bosh | \
  jq -r -s '.[] | map({ key: ("google_compute_firewallasdf." + .name), value: .name }) | from_entries' \
  > "${output_dir}/firewall-rules.json"

echo "Found the following rules:"
cat "${output_dir}/firewall-rules.json"
