#!/bin/bash

set -eu

deployments_dir="$( cd "$( dirname "$0" )" && cd ../../.. && pwd )"
workspace_dir="$( cd "${deployments_dir}/.." && pwd )"

# env
: ${BOSH_DIRECTOR_SECRETS:?}
: ${RELEASE_GLOBS:?}
: ${STEMCELL_GLOB:?}

yaml_to_json() {
  echo "$1" | ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))'
}

secrets_json="$(yaml_to_json "${BOSH_DIRECTOR_SECRETS}")"

# inputs
bosh_cli=$( echo ${workspace_dir}/bosh-cli/bosh-cli-* )
chmod +x "${bosh_cli}"

echo "Updating releases..."
export BOSH_ENVIRONMENT="$( echo "${secrets_json}" | jq -e -r .director_hostname )"
export BOSH_USER="$( echo "${secrets_json}" | jq -e -r .director_admin_username )"
export BOSH_PASSWORD="$( echo "${secrets_json}" | jq -e -r .director_admin_password )"

IFS=' '; for glob in ${RELEASE_GLOBS}; do
  files=(${glob})
  for file in "${files[@]}"; do
    echo "Uploading release '${file}'..."
    ${bosh_cli} -n upload-release "${file}"
  done
done

files=(${STEMCELL_GLOB})
file="${files[0]}"
echo "Uploading stemcell '${file}'..."
${bosh_cli} -n upload-stemcell "${file}"

echo "Successfully uploaded assets!"
