---
name: bosh

releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.3
    sha1: e4442afcc64123e11f2b33cc2be799a0b59207d0
  - name: bosh-google-cpi
    url: https://storage.googleapis.com/bosh-cpi-artifacts/bosh-google-cpi-25.1.0.tgz
    sha1: f99dff6860731921282dd1bcd097a74beaeb72a4

resource_pools:
  - name: vms
    network: private
    stemcell:
      url: https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.5-google-kvm-ubuntu-trusty-go_agent.tgz
      sha1: b7ed64f1a929b9a8e906ad5faaed73134dc68c53
    cloud_properties:
      zone: ((google_zone))
      machine_type: g1-small
      root_disk_size_gb: 40
      root_disk_type: pd-standard
      tags:
        - bosh-external
      service_scopes:
        - compute
        - devstorage.full_control

disk_pools:
  - name: disks
    disk_size: 20_000
    cloud_properties:
      type: pd-standard

networks:
  - name: public
    type: vip
  - name: private
    type: manual
    subnets:
    - range: 10.0.0.0/24
      gateway: 10.0.0.1
      static: [10.0.0.3-10.0.0.7]
      cloud_properties:
        network_name: bosh
        subnetwork_name: bosh
        tags:
          - bosh-internal

jobs:
  - name: bosh
    instances: 1

    templates:
      - name: nats
        release: bosh
      - name: postgres
        release: bosh
      - name: blobstore
        release: bosh
      - name: director
        release: bosh
      - name: health_monitor
        release: bosh
      - name: google_cpi
        release: bosh-google-cpi

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        static_ips: [10.0.0.6]
        default:
          - dns
          - gateway
      - name: public
        static_ips: [((external_ip))]

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: ((nats_password))

      postgres: &db
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: ((postgres_password))
        database: bosh
        adapter: postgres

      blobstore:
        address: 10.0.0.6
        port: 25250
        provider: dav
        director:
          user: director
          password: ((blobstore_director_password))
        agent:
          user: agent
          password: ((blobstore_agent_password))

      director:
        address: 127.0.0.1
        name: director-gce
        db: *db
        cpi_job: google_cpi
        user_management:
          provider: local
          local:
            users:
              - name: admin
                password: ((director_admin_password))
              - name: hm
                password: ((director_hm_password))
        ssl:
          cert: ((ssl_cert))
          key: ((ssl_key))
      hm:
        director_account:
          user: hm
          password: ((director_hm_password))
        resurrector_enabled: true

      google: &google_properties
        project: ((google_project_id))

      agent:
        mbus: ((agent_nats))

      ntp: &ntp
        - 169.254.169.254

cloud_provider:
  template:
    name: google_cpi
    release: bosh-google-cpi

  ssh_tunnel:
    host: ((external_ip))
    port: 22
    user: vcap
    private_key: ((ssh_private_key))

  mbus: ((cloud_provider_mbus))

  properties:
    google: *google_properties
    agent: {mbus: ((cloud_provider_agent_mbus)) }
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
