---
jobs:
  - name: update-terraform
    plan:
      - get: deployments-src
      - put: terraform
        params:
          env_name: lyle-deployments
          terraform_source: deployments-src/terraform/

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
  - name: deployments-src
    type: git
    source:
      uri: https://github.com/ljfranklin/deployments
      branch: master
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        projectid: {{gce_project_id}}
        gce_credentials_json: {{gce_credentials_json}}
        deployments_bucket_name: {{deployments_bucket_name}}
        cloudflare_email: {{cloudflare_email}}
        cloudflare_token: {{cloudflare_token}}
        cloudflare_domain: {{cloudflare_domain}}
