---
jobs:
  - name: update-terraform
    plan:
      - get: deployments-src
      - put: terraform
        params:
          env_name: lyle-deployments
          terraform_source: deployments-src/terraform/

  - name: update-director
    plan:
      - aggregate:
        - get: deployments-src
        - get: stemcell
        - get: bosh-release
        - get: cpi-release
        - get: bosh-cli
        - get: terraform
      - task: update-director
        file: deployments-src/ci/setup-env/tasks/deploy-director.yml
        params:
          BOSH_DIRECTOR_SECRETS: {{bosh_director_secrets}}
        ensure:
          put: deployments-src
          params:
            repository: updated-deployments-src/
            rebase: true

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
  - name: deployments-src
    type: git
    source:
      uri: git@github.com:ljfranklin/deployments.git
      private_key: {{github_deploy_key}}
      branch: master
  - name: stemcell
    type: s3
    source:
      bucket: bosh-gce-light-stemcells
      regexp: light-bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent.tgz
  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-google-cpi-release
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{deployments_bucket_name}}
        bucket_path: terraform/
        access_key_id: {{storage_access_key}}
        secret_access_key: {{storage_secret_key}}
        endpoint: https://storage.googleapis.com
      vars:
        projectid: {{gce_project_id}}
        gce_credentials_json: {{gce_credentials_json}}
        deployments_bucket_name: {{deployments_bucket_name}}
        cloudflare_email: {{cloudflare_email}}
        cloudflare_token: {{cloudflare_token}}
        cloudflare_domain: {{cloudflare_domain}}
