---
name: vault

releases:
  - name: vault
    url: https://bosh.io/d/github.com/cloudfoundry-community/vault-boshrelease?v=0.4.1
    sha1: 1e44414639cfec645b2a6463f2aad2573752e65f
    version: 0.4.1
  - name: consul
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/consul-release?v=115
    sha1: 42fc3f437c62855c27c2e2d2edebff263e5aafbd
    version: 115
  - name: nginx
    url: https://github.com/cloudfoundry-community/nginx-release/releases/download/v4/nginx-4.tgz
    sha1: cc0523d6b13d0e7cfed324610843d27a2df66826
    version: 4

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
  - name: vault
    instances: 1
    vm_type: small
    stemcell: trusty
    azs: [z1]
    persistent_disk_type: 10GB
    networks:
      - name: public-vault
        default: [dns, gateway]
      - name: floating
        static_ips: [((vault_floating_ip))]
    jobs:
      - name: vault
        release: vault
        properties:
          vault:
            listener:
              tcp:
                tls:
                  certificate: ((tls_cert))
                  key: ((tls_key))
            backend:
              use_consul: true
      - name: consul_agent
        release: consul
        properties:
          consul:
            agent:
              domain: cf.internal
              mode: server
              servers:
                lan:
                  - 127.0.0.1
            ca_cert: ((consul_ca_cert))
            server_cert: ((consul_server_cert))
            server_key: ((consul_server_key))
            agent_cert: ((consul_agent_cert))
            agent_key: ((consul_agent_key))
            encrypt_keys: [((consul_encryption_key))]
      - name: nginx
        release: nginx
        properties:
          nginx_conf: |
            worker_processes  1;
            events {
              worker_connections  1024;
            }
            http {
              include /var/vcap/packages/nginx/conf/mime.types;
              # redirect HTTP to HTTPS
              server {
                server_name _;
                listen 80 default_server;
                return 301 https://$host$request_uri;
              }
              server {
                server_name _;
                listen              443 ssl default_server;
                ssl_certificate     /var/vcap/jobs/nginx/etc/ssl_chained.crt.pem;
                ssl_certificate_key /var/vcap/jobs/nginx/etc/ssl.key.pem;
                root /var/vcap/store/nginx;
                index index.shtml index.html index.htm;
              }
            }
          ssl_chained_cert: ((tls_cert))
          ssl_key: ((tls_key))
          pre_start: |
            #!/bin/bash -ex
            NGINX_DIR=/var/vcap/store/nginx
            rm -rf "${NGINX_DIR}"
            mkdir -p "${NGINX_DIR}"
            curl -L https://github.com/AMeng/vault-web/archive/v0.1.tar.gz |
              tar xzf - -C "${NGINX_DIR} --strip-components=1 -- src/"
            chown -R vcap:vcap "${NGINX_DIR}"

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
