---
name: concourse

releases:
- name: concourse
  version: latest
- name: postgres
  version: 25
  #  version: latest
- name: bpm
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: concourse
  instances: 1
  vm_type: concourse
  stemcell: xenial
  azs: [z1]
  persistent_disk_type: 10GB
  networks:
    - name: public-concourse
      default: [dns, gateway]
    - name: floating
      static_ips: [((concourse_floating_ip))]
  jobs:
    - release: bpm
      name: bpm
      properties: {}
    - name: web
      release: concourse
      properties:
        external_url: ((concourse_url))
        bind_port: 80
        tls_bind_port: 443
        tls_cert: ((concourse_ssl_cert))
        tls_key: ((concourse_ssl_key))
        token_signing_key: ((token_signing_key))
        postgresql:
          database: atc
          role:
            name: atc
            password: ((concourse_db_password))
        github_auth:
          client_id: ((github_client_id))
          client_secret: ((github_client_secret))
        main_team:
          auth:
            github:
              users:
              - ((github_username))
        token_signing_key: ((token_signing_key))
        worker_gateway:
          host_key: ((tsa_host_key))
          authorized_keys: [((worker_key.public_key))]
    - name: postgres
      release: postgres
      properties:
        databases:
          port: 5432
          databases:
          - name: atc
          roles:
          - name: atc
            password: ((concourse_db_password))
    - name: worker
      release: concourse
      properties:
        drain_timeout: 10m
        worker_gateway:
          host_public_key: ((tsa_host_key.public_key))
          worker_key: ((worker_key))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
  - name: concourse_db_password
    type: password
  - name: token_signing_key
    type: rsa
  - name: tsa_host_key
    type: ssh
  - name: worker_key
    type: ssh
